/* empty css                      */import{a as S,S as v,i}from"./assets/vendor-9md0t_4N.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const q="25786434-348adb767e319176b4ad356ea",B="https://pixabay.com/api/";async function m(r,e=1){const a={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await S.get(B,{params:a})).data}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const e=r.map(({webformatURL:a,largeImageURL:n,tags:t,likes:o,views:s,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${n}" class="gallery-link">
          <img src="${a}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),M.refresh()}function $(){f.innerHTML=""}function p(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function P(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}const E=document.querySelector(".form"),O=document.querySelector(".load-more");let c="",d=1,l=0;E.addEventListener("submit",x);O.addEventListener("click",A);async function x(r){if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),!c){i.error({message:"Please enter a search term"});return}d=1,l=0,u(),$(),p();try{const e=await m(c,d);if(l=e.totalHits,e.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),e.hits.length<l?P():u()}catch(e){i.error({message:"Something went wrong while fetching images."}),console.error(e)}finally{L()}}async function A(){d+=1,p();try{const r=await m(c,d);g(r.hits),C(),document.querySelectorAll(".gallery-item").length>=l&&(u(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){i.error({message:"Error loading more images."}),console.error(r)}finally{L()}}function C(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
